### ISSUE TITLE
source code for DR_UDP_Monitor.exe

### ISSUE THREAD

**Issue by SonnyWalkman** [andy5211d/DR2TVOverlay#1]
Hello @andy5211d,
Do you happen to have the source code for you monitoring tool?  

I'm writing a script to add simple lower thirds for my lua script and like to modify your Monitor.exe to monitor the udp commands from my client app.  I'm using go for programming my client.

**Comment by andy5211d** [comment]
Hi.  Yes I do.  Nothing special just me learning how to get at UDP ports and the Delphi version is the only one I could get to work correctly.   Could not get c++ or C# to mulit-thread correctly even with all the web help!   When back home I'll put the Delphi source in this repo.  Won't be until next week sometime.

**Comment by andy5211d** [comment]
Source uploaded to Tools folder

**Comment by SonnyWalkman** [comment]
Thanks Andy,
I’ve managed to get away with using ncat for windows and sent commands to
my script.

Has been working without issues however be good to see how you put it
together.

Programming in lua been interesting so far enjoying getting audio wav
playing using media resource. Most what I wanted to get done I’ve learn by
poaching bit here and there.

Question? Does your script send acknowledgments back to your client program?

Cheer

Rob

**Comment by andy5211d** [comment]
Hi Rob,

 

The UDP monitor was really an exercise in understanding UDP comms and also to get my Community version of Delphi to do something useful.   

 

I’m part of a team that will be taking over Diverecorder (www.diverecorder.co.uk <http://www.diverecorder.co.uk> ) maintenance (and hopefully development) when the Author retires in a few years.   He has written the suite in Delphi and as Delphi (Pascal)  was the language we used at Uni (40 years ago now!) thought I’d get into a bit of software.   Not sure this was a good idea…

 

Still my UDP monitor software does not do any ack and neither does my OBS scripts.   UDP being a ‘fire and forget’ protocol and most of Diverecorders comms is UDP.  That said I will have to get into the more complex protocol as I need my OBS scripts to get the Start List and Results List for display which can only be got from Diverecorder by an IP session.   

 

Like you most of my programmes are copy and paste from somewhere on the web!  But been playing with Bing AI in MS’s VS Code which is an interesting diversion…

 

Hmm, ncat, not visual enough for me but I do use Wireshark when I can be bothered to get it going!  Something that I’ve found useful is Packet Sender, www.packetsender.com <http://www.packetsender.com>  as it can replicate a lot of what I need to monitor and receive  in OBS without having to run the originating software.    

 

Cheers,  Andy.
